#DeltaRealms dExtras plugin is a quality of life plugin for DeltaRealms. It implements various small features,
#irons out kinks in other plugins, and implements other qol features.

#Gives "betterrtp.bypass.cooldown" for 10 minutes to new players so that they won't quit the server
#if they die off the bat, didn't set a home, and can't rtp again.
#(Requires server restart upon change).
FirstJoin: true

#Plays a firework sounds to Naspo when a new player joins the server.
NewPlayerPingNaspo: true

#Tracks new join analytics from various subdomains.
DiscoveryAnalytics:
  started-tracking: "dd/mm/yyyy"
  sub-domains:
    #Add as many subdomains as you wish, then reload the plugin.
    play: 0
    example: 0

#Prompts players to download the server texture pack.
#If enabled, pack-url should contain a valid link.
pack-prompt:
  enabled: false
  #Compatible with Dropbox
  pack-url: ""

messages:
  general:
    prefix: "&8[&6&ldExtras&8] &r"
    reload: "&7All configurations reloaded."
    no-permission: "&cYou do not have permission."
  first-join:
    home-reminder: "&eRemember to set a home! &6/sethome <home>"